Fix clang-tidy run
Clang-tidy was failing because it was run on a build that
was created by gcc. So, some gcc flags caused clang-tidy fail:

```
Error while processing /opt/project/src/filcompare.cpp.
error: unknown warning option '-Wduplicated-branches' [clang-diagnostic-unknown-warning-option]
error: unknown warning option '-Wduplicated-cond' [clang-diagnostic-unknown-warning-option]
error: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [clang-diagnostic-unknown-warning-option]
error: unknown warning option '-Wuseless-cast' [clang-diagnostic-unknown-warning-option]
```

In order to fix this, we need to build the filcompare with clang first.